package com.att.edispute.rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ATTInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Double adjustmentAmount6MonthsRemain;
	private java.lang.Double adjustmentAmount6MonthsTotal;
	private java.lang.Double adjustmentAmountWeeklyRemain;
	private java.lang.Double adjustmentAmountWeeklyTotal;
	private java.lang.Double adjustmentAmountMonthlyTotal;

	private java.lang.Double adjustmentAmountMonthlyRemain;

	public ATTInfo() {
	}

	public java.lang.Double getAdjustmentAmount6MonthsRemain() {
		return this.adjustmentAmount6MonthsRemain;
	}

	public void setAdjustmentAmount6MonthsRemain(
			java.lang.Double adjustmentAmount6MonthsRemain) {
		this.adjustmentAmount6MonthsRemain = adjustmentAmount6MonthsRemain;
	}

	public java.lang.Double getAdjustmentAmount6MonthsTotal() {
		return this.adjustmentAmount6MonthsTotal;
	}

	public void setAdjustmentAmount6MonthsTotal(
			java.lang.Double adjustmentAmount6MonthsTotal) {
		this.adjustmentAmount6MonthsTotal = adjustmentAmount6MonthsTotal;
	}

	public java.lang.Double getAdjustmentAmountWeeklyRemain() {
		return this.adjustmentAmountWeeklyRemain;
	}

	public void setAdjustmentAmountWeeklyRemain(
			java.lang.Double adjustmentAmountWeeklyRemain) {
		this.adjustmentAmountWeeklyRemain = adjustmentAmountWeeklyRemain;
	}

	public java.lang.Double getAdjustmentAmountWeeklyTotal() {
		return this.adjustmentAmountWeeklyTotal;
	}

	public void setAdjustmentAmountWeeklyTotal(
			java.lang.Double adjustmentAmountWeeklyTotal) {
		this.adjustmentAmountWeeklyTotal = adjustmentAmountWeeklyTotal;
	}

	public java.lang.Double getAdjustmentAmountMonthlyTotal() {
		return this.adjustmentAmountMonthlyTotal;
	}

	public void setAdjustmentAmountMonthlyTotal(
			java.lang.Double adjustmentAmountMonthlyTotal) {
		this.adjustmentAmountMonthlyTotal = adjustmentAmountMonthlyTotal;
	}

	public java.lang.Double getAdjustmentAmountMonthlyRemain() {
		return this.adjustmentAmountMonthlyRemain;
	}

	public void setAdjustmentAmountMonthlyRemain(
			java.lang.Double adjustmentAmountMonthlyRemain) {
		this.adjustmentAmountMonthlyRemain = adjustmentAmountMonthlyRemain;
	}

	public ATTInfo(java.lang.Double adjustmentAmount6MonthsRemain,
			java.lang.Double adjustmentAmount6MonthsTotal,
			java.lang.Double adjustmentAmountWeeklyRemain,
			java.lang.Double adjustmentAmountWeeklyTotal,
			java.lang.Double adjustmentAmountMonthlyTotal,
			java.lang.Double adjustmentAmountMonthlyRemain) {
		this.adjustmentAmount6MonthsRemain = adjustmentAmount6MonthsRemain;
		this.adjustmentAmount6MonthsTotal = adjustmentAmount6MonthsTotal;
		this.adjustmentAmountWeeklyRemain = adjustmentAmountWeeklyRemain;
		this.adjustmentAmountWeeklyTotal = adjustmentAmountWeeklyTotal;
		this.adjustmentAmountMonthlyTotal = adjustmentAmountMonthlyTotal;
		this.adjustmentAmountMonthlyRemain = adjustmentAmountMonthlyRemain;
	}

}