package com.att.edispute.rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CustomerEligibilityInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CUSTOMERELIGIBILITYINFO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CUSTOMERELIGIBILITYINFO_ID_GENERATOR", sequenceName = "CUSTOMERELIGIBILITYINFO_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String billingAccount;

	private java.lang.Short highActivityIndicator;

	private java.lang.Double histAdjustmentsAmmount;

	private java.lang.Integer histAdjustmentsNumber;

	private java.lang.String chargeCode;

	private java.lang.Boolean billOverDue;

	private java.lang.String accountStatus;

	private java.lang.Boolean churnIndicator;

	private java.lang.Double adjustmentAmountWeekly;

	private java.lang.Double adjustmentAmountMonthly;

	private java.lang.Double adjustmentAmount6Months;

	private java.lang.Double adjustmentAmountMonthlyRemain;

	private java.lang.Double adjustmentAmountWeeklyRemain;

	private java.lang.Double adjustmentAmount6MonthsRemain;

	private java.lang.Short adjustmentsLast6Months;

	private java.lang.Short adjustmentsLastMonth;

	private java.lang.Short adjustmentsLastWeek;

	private java.lang.Double monthlySpent;

	public CustomerEligibilityInfo() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getBillingAccount() {
		return this.billingAccount;
	}

	public void setBillingAccount(java.lang.String billingAccount) {
		this.billingAccount = billingAccount;
	}

	public java.lang.Short getHighActivityIndicator() {
		return this.highActivityIndicator;
	}

	public void setHighActivityIndicator(java.lang.Short highActivityIndicator) {
		this.highActivityIndicator = highActivityIndicator;
	}

	public java.lang.Double getHistAdjustmentsAmmount() {
		return this.histAdjustmentsAmmount;
	}

	public void setHistAdjustmentsAmmount(
			java.lang.Double histAdjustmentsAmmount) {
		this.histAdjustmentsAmmount = histAdjustmentsAmmount;
	}

	public java.lang.Integer getHistAdjustmentsNumber() {
		return this.histAdjustmentsNumber;
	}

	public void setHistAdjustmentsNumber(java.lang.Integer histAdjustmentsNumber) {
		this.histAdjustmentsNumber = histAdjustmentsNumber;
	}

	public java.lang.String getChargeCode() {
		return this.chargeCode;
	}

	public void setChargeCode(java.lang.String chargeCode) {
		this.chargeCode = chargeCode;
	}

	public java.lang.Boolean getBillOverDue() {
		return this.billOverDue;
	}

	public void setBillOverDue(java.lang.Boolean billOverDue) {
		this.billOverDue = billOverDue;
	}

	public java.lang.String getAccountStatus() {
		return this.accountStatus;
	}

	public void setAccountStatus(java.lang.String accountStatus) {
		this.accountStatus = accountStatus;
	}

	public java.lang.Boolean getChurnIndicator() {
		return this.churnIndicator;
	}

	public void setChurnIndicator(java.lang.Boolean churnIndicator) {
		this.churnIndicator = churnIndicator;
	}

	public java.lang.Double getAdjustmentAmountWeekly() {
		return this.adjustmentAmountWeekly;
	}

	public void setAdjustmentAmountWeekly(
			java.lang.Double adjustmentAmountWeekly) {
		this.adjustmentAmountWeekly = adjustmentAmountWeekly;
	}

	public java.lang.Double getAdjustmentAmountMonthly() {
		return this.adjustmentAmountMonthly;
	}

	public void setAdjustmentAmountMonthly(
			java.lang.Double adjustmentAmountMonthly) {
		this.adjustmentAmountMonthly = adjustmentAmountMonthly;
	}

	public java.lang.Double getAdjustmentAmount6Months() {
		return this.adjustmentAmount6Months;
	}

	public void setAdjustmentAmount6Months(
			java.lang.Double adjustmentAmount6Months) {
		this.adjustmentAmount6Months = adjustmentAmount6Months;
	}

	public java.lang.Double getAdjustmentAmountMonthlyRemain() {
		return this.adjustmentAmountMonthlyRemain;
	}

	public void setAdjustmentAmountMonthlyRemain(
			java.lang.Double adjustmentAmountMonthlyRemain) {
		this.adjustmentAmountMonthlyRemain = adjustmentAmountMonthlyRemain;
	}

	public java.lang.Double getAdjustmentAmountWeeklyRemain() {
		return this.adjustmentAmountWeeklyRemain;
	}

	public void setAdjustmentAmountWeeklyRemain(
			java.lang.Double adjustmentAmountWeeklyRemain) {
		this.adjustmentAmountWeeklyRemain = adjustmentAmountWeeklyRemain;
	}

	public java.lang.Double getAdjustmentAmount6MonthsRemain() {
		return this.adjustmentAmount6MonthsRemain;
	}

	public void setAdjustmentAmount6MonthsRemain(
			java.lang.Double adjustmentAmount6MonthsRemain) {
		this.adjustmentAmount6MonthsRemain = adjustmentAmount6MonthsRemain;
	}

	public java.lang.Short getAdjustmentsLast6Months() {
		return this.adjustmentsLast6Months;
	}

	public void setAdjustmentsLast6Months(java.lang.Short adjustmentsLast6Months) {
		this.adjustmentsLast6Months = adjustmentsLast6Months;
	}

	public java.lang.Short getAdjustmentsLastMonth() {
		return this.adjustmentsLastMonth;
	}

	public void setAdjustmentsLastMonth(java.lang.Short adjustmentsLastMonth) {
		this.adjustmentsLastMonth = adjustmentsLastMonth;
	}

	public java.lang.Short getAdjustmentsLastWeek() {
		return this.adjustmentsLastWeek;
	}

	public void setAdjustmentsLastWeek(java.lang.Short adjustmentsLastWeek) {
		this.adjustmentsLastWeek = adjustmentsLastWeek;
	}

	public java.lang.Double getMonthlySpent() {
		return this.monthlySpent;
	}

	public void setMonthlySpent(java.lang.Double monthlySpent) {
		this.monthlySpent = monthlySpent;
	}

	public CustomerEligibilityInfo(java.lang.Long id,
			java.lang.String billingAccount,
			java.lang.Short highActivityIndicator,
			java.lang.Double histAdjustmentsAmmount,
			java.lang.Integer histAdjustmentsNumber,
			java.lang.String chargeCode, java.lang.Boolean billOverDue,
			java.lang.String accountStatus, java.lang.Boolean churnIndicator,
			java.lang.Double adjustmentAmountWeekly,
			java.lang.Double adjustmentAmountMonthly,
			java.lang.Double adjustmentAmount6Months,
			java.lang.Double adjustmentAmountMonthlyRemain,
			java.lang.Double adjustmentAmountWeeklyRemain,
			java.lang.Double adjustmentAmount6MonthsRemain,
			java.lang.Short adjustmentsLast6Months,
			java.lang.Short adjustmentsLastMonth,
			java.lang.Short adjustmentsLastWeek, java.lang.Double monthlySpent) {
		this.id = id;
		this.billingAccount = billingAccount;
		this.highActivityIndicator = highActivityIndicator;
		this.histAdjustmentsAmmount = histAdjustmentsAmmount;
		this.histAdjustmentsNumber = histAdjustmentsNumber;
		this.chargeCode = chargeCode;
		this.billOverDue = billOverDue;
		this.accountStatus = accountStatus;
		this.churnIndicator = churnIndicator;
		this.adjustmentAmountWeekly = adjustmentAmountWeekly;
		this.adjustmentAmountMonthly = adjustmentAmountMonthly;
		this.adjustmentAmount6Months = adjustmentAmount6Months;
		this.adjustmentAmountMonthlyRemain = adjustmentAmountMonthlyRemain;
		this.adjustmentAmountWeeklyRemain = adjustmentAmountWeeklyRemain;
		this.adjustmentAmount6MonthsRemain = adjustmentAmount6MonthsRemain;
		this.adjustmentsLast6Months = adjustmentsLast6Months;
		this.adjustmentsLastMonth = adjustmentsLastMonth;
		this.adjustmentsLastWeek = adjustmentsLastWeek;
		this.monthlySpent = monthlySpent;
	}

}