package com.att.edispute.rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class eDisputeResolution implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("billAccount")
	private java.lang.String billAccount;
	@org.kie.api.definition.type.Label("creditAmmount")
	private java.lang.Double creditAmmount;
	@org.kie.api.definition.type.Label("shortExplanation")
	private java.lang.String shortExplanation;
	@org.kie.api.definition.type.Label("explanation")
	private java.lang.String explanation;
	@org.kie.api.definition.type.Label("status")
	private java.lang.Boolean status;
	@org.kie.api.definition.type.Label("displayValue")
	private java.lang.String displayValue;

	@org.kie.api.definition.type.Label("displayTitle")
	private java.lang.String displayTitle;

	@org.kie.api.definition.type.Label("displaySubTitle")
	private java.lang.String displaySubTitle;

	@org.kie.api.definition.type.Label("displayDetailText")
	private java.lang.String displayDetailText;

	private java.lang.String displayNote;

	public eDisputeResolution() {
	}

	public java.lang.String getBillAccount() {
		return this.billAccount;
	}

	public void setBillAccount(java.lang.String billAccount) {
		this.billAccount = billAccount;
	}

	public java.lang.Double getCreditAmmount() {
		return this.creditAmmount;
	}

	public void setCreditAmmount(java.lang.Double creditAmmount) {
		this.creditAmmount = creditAmmount;
	}

	public java.lang.String getShortExplanation() {
		return this.shortExplanation;
	}

	public void setShortExplanation(java.lang.String shortExplanation) {
		this.shortExplanation = shortExplanation;
	}

	public java.lang.String getExplanation() {
		return this.explanation;
	}

	public void setExplanation(java.lang.String explanation) {
		this.explanation = explanation;
	}

	public java.lang.Boolean getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Boolean status) {
		this.status = status;
	}

	public java.lang.String getDisplayValue() {
		return this.displayValue;
	}

	public void setDisplayValue(java.lang.String displayValue) {
		this.displayValue = displayValue;
	}

	public java.lang.String getDisplayTitle() {
		return this.displayTitle;
	}

	public void setDisplayTitle(java.lang.String displayTitle) {
		this.displayTitle = displayTitle;
	}

	public java.lang.String getDisplaySubTitle() {
		return this.displaySubTitle;
	}

	public void setDisplaySubTitle(java.lang.String displaySubTitle) {
		this.displaySubTitle = displaySubTitle;
	}

	public java.lang.String getDisplayDetailText() {
		return this.displayDetailText;
	}

	public void setDisplayDetailText(java.lang.String displayDetailText) {
		this.displayDetailText = displayDetailText;
	}

	public java.lang.String getDisplayNote() {
		return this.displayNote;
	}

	public void setDisplayNote(java.lang.String displayNote) {
		this.displayNote = displayNote;
	}

	public eDisputeResolution(java.lang.String billAccount,
			java.lang.Double creditAmmount, java.lang.String shortExplanation,
			java.lang.String explanation, java.lang.Boolean status,
			java.lang.String displayValue, java.lang.String displayTitle,
			java.lang.String displaySubTitle,
			java.lang.String displayDetailText, java.lang.String displayNote) {
		this.billAccount = billAccount;
		this.creditAmmount = creditAmmount;
		this.shortExplanation = shortExplanation;
		this.explanation = explanation;
		this.status = status;
		this.displayValue = displayValue;
		this.displayTitle = displayTitle;
		this.displaySubTitle = displaySubTitle;
		this.displayDetailText = displayDetailText;
		this.displayNote = displayNote;
	}

}